name = "crm-bot"
main = "src/workers/cloudflare.js"
compatibility_date = "2024-01-01"
node_compat = true

# Replace with your Cloudflare account ID
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# Workers.dev subdomain (optional)
workers_dev = true
# route = "https://your-domain.com/slack/*"

[vars]
NODE_ENV = "production"

# KV Namespaces for caching (optional)
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_ID"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Environment-specific settings
[env.staging]
name = "crm-bot-staging"
vars = { NODE_ENV = "staging" }

[env.production]
name = "crm-bot-production"
vars = { NODE_ENV = "production" }

# Secrets to be set via wrangler CLI:
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_SIGNING_SECRET  
# wrangler secret put SLACK_APP_TOKEN
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put ATTIO_API_KEY
# wrangler secret put MONGODB_URI