name = "crm-bot"
main = "src/workers/cloudflare-full.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Your Cloudflare account ID
account_id = "f6413eebf7a74012c2411824d33838bd"

# Workers.dev subdomain (optional)
workers_dev = true
# route = "https://your-domain.com/slack/*"

[vars]
NODE_ENV = "production"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "29fb6d3707a14b96a05f076b78725303"
preview_id = "a02f44a3674b42b79d05a40e32c8e8f6"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Environment-specific settings
[env.staging]
name = "crm-bot-staging"
vars = { NODE_ENV = "staging" }

[env.production]
name = "crm-bot-production"
vars = { NODE_ENV = "production" }

# Secrets to be set via wrangler CLI:
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_SIGNING_SECRET  
# wrangler secret put SLACK_APP_TOKEN
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put ATTIO_API_KEY
# wrangler secret put MONGODB_URI